AZURE_AI_FOUNDRY_ENDPOINT = "https://azureaiserviceshubdemo.services.ai.azure.com/api/projects/azureaiserviceshubdemo-project"
AZURE_AI_FOUNDRY_AGENT_ID = "asst_Mlew8M6WPiUMrQlPgEg5ZRMo"

# Azure Service Principal for Streamlit Cloud Authentication
AZURE_CLIENT_ID = "0c449aa6-2dc1-4946-8278-ce748769d7fc"
AZURE_CLIENT_SECRET = "EeN8Q~Nn2EUeSrRx~n5na7n4MrU03H9zEVSHVcvP"
AZURE_TENANT_ID = "603f70f9-1661-464b-b868-585fe260812a"
